// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/skv2/api/multicluster/discovery/v1alpha1/aws_discovery.proto

package v1alpha1

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for AwsDiscoveryDirectiveSpec
func (this *AwsDiscoveryDirectiveSpec) MarshalJSON() ([]byte, error) {
	str, err := AwsDiscoveryMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AwsDiscoveryDirectiveSpec
func (this *AwsDiscoveryDirectiveSpec) UnmarshalJSON(b []byte) error {
	return AwsDiscoveryUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AwsDiscoveryDirectiveSpec_AwsResourceSelector
func (this *AwsDiscoveryDirectiveSpec_AwsResourceSelector) MarshalJSON() ([]byte, error) {
	str, err := AwsDiscoveryMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AwsDiscoveryDirectiveSpec_AwsResourceSelector
func (this *AwsDiscoveryDirectiveSpec_AwsResourceSelector) UnmarshalJSON(b []byte) error {
	return AwsDiscoveryUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AwsDiscoveryDirectiveSpec_AwsResourceSelector_Matcher
func (this *AwsDiscoveryDirectiveSpec_AwsResourceSelector_Matcher) MarshalJSON() ([]byte, error) {
	str, err := AwsDiscoveryMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AwsDiscoveryDirectiveSpec_AwsResourceSelector_Matcher
func (this *AwsDiscoveryDirectiveSpec_AwsResourceSelector_Matcher) UnmarshalJSON(b []byte) error {
	return AwsDiscoveryUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AwsDiscoveryDirectiveStatus
func (this *AwsDiscoveryDirectiveStatus) MarshalJSON() ([]byte, error) {
	str, err := AwsDiscoveryMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AwsDiscoveryDirectiveStatus
func (this *AwsDiscoveryDirectiveStatus) UnmarshalJSON(b []byte) error {
	return AwsDiscoveryUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	AwsDiscoveryMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	AwsDiscoveryUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
