// Code generated by skv2. DO NOT EDIT.

// Package v1alpha1 contains API Schema definitions for the discovery.multicluster.solo.io v1alpha1 API group
// +k8s:deepcopy-gen=package,register
// +groupName=discovery.multicluster.solo.io
package v1alpha1
