// Code generated by skv2. DO NOT EDIT.

// This file contains generated Deepcopy methods for proto-based Spec and Status fields

package v1alpha1

import (
	proto "github.com/gogo/protobuf/proto"
)

// DeepCopyInto for the AwsDiscoveryDirective.Spec
func (in *AwsDiscoveryDirectiveSpec) DeepCopyInto(out *AwsDiscoveryDirectiveSpec) {
	p := proto.Clone(in).(*AwsDiscoveryDirectiveSpec)
	*out = *p
}

// DeepCopyInto for the AwsDiscoveryDirective.Status
func (in *AwsDiscoveryDirectiveStatus) DeepCopyInto(out *AwsDiscoveryDirectiveStatus) {
	p := proto.Clone(in).(*AwsDiscoveryDirectiveStatus)
	*out = *p
}
