changelog:
- type: NON_USER_FACING
  description: >
    Error on nil kubeconfigs when registering clusters. When registering clusters, we now create
    the KubernetesCluster CRD on the management cluster, which requires us to have the management
    cluster's kube config passed in to the registration options.
  issueLink: https://github.com/solo-io/skv2/issues/184
- type: NON_USER_FACING
  description: >
    Make SnapshotTemplateParameters ConstructTemplate function public.
  issueLink: https://github.com/solo-io/skv2/issues/184