// Code generated by skv2. DO NOT EDIT.

// Definitions for the Kubernetes types
package v1

import (
    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
    "k8s.io/apimachinery/pkg/runtime/schema")

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status

// GroupVersionKind for Paint
var PaintGVK = schema.GroupVersionKind{
    Group: "things.test.io",
    Version: "v1",
    Kind: "Paint",
}

// Paint is the Schema for the paint API
type Paint struct {
    metav1.TypeMeta   `json:",inline"`
    metav1.ObjectMeta `json:"metadata,omitempty"`

    Spec PaintSpec `json:"spec,omitempty"`
    Status PaintStatus `json:"status,omitempty"`
}

// GVK returns the GroupVersionKind associated with the resource type.
func (Paint)  GVK() schema.GroupVersionKind {
	return PaintGVK
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// PaintList contains a list of Paint
type PaintList struct {
    metav1.TypeMeta `json:",inline"`
    metav1.ListMeta `json:"metadata,omitempty"`
    Items           []Paint `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
// +genclient:noStatus

// GroupVersionKind for ClusterResource
var ClusterResourceGVK = schema.GroupVersionKind{
    Group: "things.test.io",
    Version: "v1",
    Kind: "ClusterResource",
}

// ClusterResource is the Schema for the clusterResource API
type ClusterResource struct {
    metav1.TypeMeta   `json:",inline"`
    metav1.ObjectMeta `json:"metadata,omitempty"`

    Spec ClusterResourceSpec `json:"spec,omitempty"`
}

// GVK returns the GroupVersionKind associated with the resource type.
func (ClusterResource)  GVK() schema.GroupVersionKind {
	return ClusterResourceGVK
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ClusterResourceList contains a list of ClusterResource
type ClusterResourceList struct {
    metav1.TypeMeta `json:",inline"`
    metav1.ListMeta `json:"metadata,omitempty"`
    Items           []ClusterResource `json:"items"`
}

func init() {
    SchemeBuilder.Register(&Paint{}, &PaintList{})
    SchemeBuilder.Register(&ClusterResource{}, &ClusterResourceList{})
}
