// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/skv2/api/multicluster/v1alpha1/cluster.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//Representation of a Kubernetes cluster that has been registered.
type KubernetesClusterSpec struct {
	// name of the secret which contains the kubeconfig with information to connect to the remote cluster.
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// version of kubernetes
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// cloud provider, empty if unknown
	Cloud                string   `protobuf:"bytes,3,opt,name=cloud,proto3" json:"cloud,omitempty"`
	Region               string   `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Zone                 string   `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubernetesClusterSpec) Reset()         { *m = KubernetesClusterSpec{} }
func (m *KubernetesClusterSpec) String() string { return proto.CompactTextString(m) }
func (*KubernetesClusterSpec) ProtoMessage()    {}
func (*KubernetesClusterSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_533baf1d8d7a56a7, []int{0}
}
func (m *KubernetesClusterSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesClusterSpec.Unmarshal(m, b)
}
func (m *KubernetesClusterSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesClusterSpec.Marshal(b, m, deterministic)
}
func (m *KubernetesClusterSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesClusterSpec.Merge(m, src)
}
func (m *KubernetesClusterSpec) XXX_Size() int {
	return xxx_messageInfo_KubernetesClusterSpec.Size(m)
}
func (m *KubernetesClusterSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesClusterSpec.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesClusterSpec proto.InternalMessageInfo

func (m *KubernetesClusterSpec) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *KubernetesClusterSpec) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *KubernetesClusterSpec) GetCloud() string {
	if m != nil {
		return m.Cloud
	}
	return ""
}

func (m *KubernetesClusterSpec) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *KubernetesClusterSpec) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type KubernetesClusterStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubernetesClusterStatus) Reset()         { *m = KubernetesClusterStatus{} }
func (m *KubernetesClusterStatus) String() string { return proto.CompactTextString(m) }
func (*KubernetesClusterStatus) ProtoMessage()    {}
func (*KubernetesClusterStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_533baf1d8d7a56a7, []int{1}
}
func (m *KubernetesClusterStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesClusterStatus.Unmarshal(m, b)
}
func (m *KubernetesClusterStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesClusterStatus.Marshal(b, m, deterministic)
}
func (m *KubernetesClusterStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesClusterStatus.Merge(m, src)
}
func (m *KubernetesClusterStatus) XXX_Size() int {
	return xxx_messageInfo_KubernetesClusterStatus.Size(m)
}
func (m *KubernetesClusterStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesClusterStatus.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesClusterStatus proto.InternalMessageInfo

func init() {
	proto.RegisterType((*KubernetesClusterSpec)(nil), "multicluster.solo.io.KubernetesClusterSpec")
	proto.RegisterType((*KubernetesClusterStatus)(nil), "multicluster.solo.io.KubernetesClusterStatus")
}

func init() {
	proto.RegisterFile("github.com/solo-io/skv2/api/multicluster/v1alpha1/cluster.proto", fileDescriptor_533baf1d8d7a56a7)
}

var fileDescriptor_533baf1d8d7a56a7 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4a, 0x03, 0x31,
	0x18, 0x85, 0x19, 0x9d, 0x56, 0xcc, 0x32, 0x8c, 0x1a, 0xbb, 0x10, 0xe9, 0xca, 0x8d, 0x13, 0xaa,
	0x07, 0x10, 0xec, 0x52, 0xdc, 0xe8, 0xce, 0xdd, 0x4c, 0xfc, 0x49, 0x43, 0xd3, 0xf9, 0x43, 0xf2,
	0x67, 0xa8, 0x5e, 0xc1, 0x8b, 0x78, 0x04, 0xcf, 0xe3, 0x1d, 0xdc, 0xcb, 0x24, 0x2d, 0x0a, 0xa5,
	0xbb, 0xf7, 0xbe, 0x3c, 0x1e, 0xf9, 0x1f, 0xbb, 0xd3, 0x86, 0x16, 0xb1, 0xad, 0x15, 0xae, 0x64,
	0x40, 0x8b, 0xd7, 0x06, 0x65, 0x58, 0xf6, 0x37, 0xb2, 0x71, 0x46, 0xae, 0xa2, 0x25, 0xa3, 0x6c,
	0x0c, 0x04, 0x5e, 0xf6, 0xb3, 0xc6, 0xba, 0x45, 0x33, 0x93, 0x1b, 0x50, 0x3b, 0x8f, 0x84, 0xbc,
	0xfa, 0x1f, 0xaa, 0x87, 0x8a, 0xda, 0xe0, 0xa4, 0xd2, 0xa8, 0x31, 0x05, 0xe4, 0xa0, 0x72, 0x76,
	0xc2, 0x61, 0x4d, 0x19, 0xc2, 0x9a, 0x32, 0x9b, 0x7e, 0x14, 0xec, 0xe4, 0x21, 0xb6, 0xe0, 0x3b,
	0x20, 0x08, 0xf3, 0xdc, 0xf3, 0xec, 0x40, 0xf1, 0x53, 0x36, 0x0e, 0xa0, 0x3c, 0x90, 0x28, 0x2e,
	0x8b, 0xab, 0xe3, 0xa7, 0x8d, 0xe3, 0x82, 0x1d, 0xf5, 0xe0, 0x83, 0xc1, 0x4e, 0x1c, 0xa4, 0x87,
	0xad, 0xe5, 0x15, 0x1b, 0x29, 0x8b, 0xf1, 0x55, 0x1c, 0x26, 0x9e, 0xcd, 0xd0, 0xe3, 0x41, 0x0f,
	0xf1, 0x32, 0xf7, 0x64, 0xc7, 0x39, 0x2b, 0xdf, 0xb1, 0x03, 0x31, 0x4a, 0x34, 0xe9, 0xe9, 0x39,
	0x3b, 0xdb, 0xfd, 0x0c, 0x35, 0x14, 0xc3, 0xfd, 0xe3, 0xd7, 0x4f, 0x59, 0x7c, 0x7e, 0x5f, 0x14,
	0x2f, 0xf3, 0x7d, 0x9b, 0xb9, 0xa5, 0xde, 0xd9, 0x6d, 0x3b, 0xc9, 0xdf, 0x7e, 0xf4, 0xe6, 0x20,
	0xb4, 0xe3, 0x74, 0xfe, 0xed, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x5f, 0x67, 0x3f, 0x81,
	0x01, 0x00, 0x00,
}

func (this *KubernetesClusterSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*KubernetesClusterSpec)
	if !ok {
		that2, ok := that.(KubernetesClusterSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Secret != that1.Secret {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	if this.Cloud != that1.Cloud {
		return false
	}
	if this.Region != that1.Region {
		return false
	}
	if this.Zone != that1.Zone {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *KubernetesClusterStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*KubernetesClusterStatus)
	if !ok {
		that2, ok := that.(KubernetesClusterStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
