// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/skv2/api/multicluster/v1alpha1/cluster.proto

package v1alpha1

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
	v1 "github.com/solo-io/skv2/pkg/api/core.skv2.solo.io/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//Representation of a Kubernetes cluster that has been registered.
type KubernetesClusterSpec struct {
	// name of the secret which contains the kubeconfig with information to connect to the remote cluster.
	Secret               *v1.ObjectRef `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *KubernetesClusterSpec) Reset()         { *m = KubernetesClusterSpec{} }
func (m *KubernetesClusterSpec) String() string { return proto.CompactTextString(m) }
func (*KubernetesClusterSpec) ProtoMessage()    {}
func (*KubernetesClusterSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_533baf1d8d7a56a7, []int{0}
}
func (m *KubernetesClusterSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesClusterSpec.Unmarshal(m, b)
}
func (m *KubernetesClusterSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesClusterSpec.Marshal(b, m, deterministic)
}
func (m *KubernetesClusterSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesClusterSpec.Merge(m, src)
}
func (m *KubernetesClusterSpec) XXX_Size() int {
	return xxx_messageInfo_KubernetesClusterSpec.Size(m)
}
func (m *KubernetesClusterSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesClusterSpec.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesClusterSpec proto.InternalMessageInfo

func (m *KubernetesClusterSpec) GetSecret() *v1.ObjectRef {
	if m != nil {
		return m.Secret
	}
	return nil
}

type KubernetesClusterStatus struct {
	// List of statuses about the kubernetes cluster.
	// This list allows for multiple applications/pods to record their connection status.
	Status []*v1.Status `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	// version of kubernetes
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// cloud provider, empty if unknown
	Cloud string `protobuf:"bytes,3,opt,name=cloud,proto3" json:"cloud,omitempty"`
	// Discovered information can be found here: https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/
	// Geographic location in which a kubernetes cluster resides
	Region string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	// The specific zone within a region in which a the cluster resides
	Zone                 string   `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubernetesClusterStatus) Reset()         { *m = KubernetesClusterStatus{} }
func (m *KubernetesClusterStatus) String() string { return proto.CompactTextString(m) }
func (*KubernetesClusterStatus) ProtoMessage()    {}
func (*KubernetesClusterStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_533baf1d8d7a56a7, []int{1}
}
func (m *KubernetesClusterStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesClusterStatus.Unmarshal(m, b)
}
func (m *KubernetesClusterStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesClusterStatus.Marshal(b, m, deterministic)
}
func (m *KubernetesClusterStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesClusterStatus.Merge(m, src)
}
func (m *KubernetesClusterStatus) XXX_Size() int {
	return xxx_messageInfo_KubernetesClusterStatus.Size(m)
}
func (m *KubernetesClusterStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesClusterStatus.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesClusterStatus proto.InternalMessageInfo

func (m *KubernetesClusterStatus) GetStatus() []*v1.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *KubernetesClusterStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *KubernetesClusterStatus) GetCloud() string {
	if m != nil {
		return m.Cloud
	}
	return ""
}

func (m *KubernetesClusterStatus) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *KubernetesClusterStatus) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func init() {
	proto.RegisterType((*KubernetesClusterSpec)(nil), "multicluster.solo.io.KubernetesClusterSpec")
	proto.RegisterType((*KubernetesClusterStatus)(nil), "multicluster.solo.io.KubernetesClusterStatus")
}

func init() {
	proto.RegisterFile("github.com/solo-io/skv2/api/multicluster/v1alpha1/cluster.proto", fileDescriptor_533baf1d8d7a56a7)
}

var fileDescriptor_533baf1d8d7a56a7 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x89, 0x6d, 0x57, 0x4c, 0x6f, 0xa1, 0xea, 0x5a, 0x45, 0x4a, 0x4f, 0xbd, 0x98, 0xb0,
	0xd5, 0xab, 0x08, 0x7a, 0xf0, 0x20, 0x22, 0xac, 0x37, 0x6f, 0xbb, 0x71, 0xdc, 0xc6, 0x6e, 0x3b,
	0x4b, 0xfe, 0x2c, 0xc5, 0x27, 0xea, 0x23, 0xf8, 0x3c, 0xbe, 0x83, 0x77, 0xd9, 0x64, 0x5b, 0x84,
	0xea, 0x29, 0x33, 0x5f, 0x7e, 0xf9, 0x66, 0xc8, 0x47, 0x6f, 0x0a, 0x65, 0x67, 0x2e, 0xe7, 0x12,
	0x17, 0xc2, 0x60, 0x89, 0x17, 0x0a, 0x85, 0x99, 0xd7, 0x53, 0x91, 0x55, 0x4a, 0x2c, 0x5c, 0x69,
	0x95, 0x2c, 0x9d, 0xb1, 0xa0, 0x45, 0x9d, 0x64, 0x65, 0x35, 0xcb, 0x12, 0xd1, 0x0a, 0xbc, 0xd2,
	0x68, 0x91, 0x0d, 0x7e, 0x43, 0xbc, 0xb1, 0xe0, 0x0a, 0x87, 0x83, 0x02, 0x0b, 0xf4, 0x80, 0x68,
	0xaa, 0xc0, 0x0e, 0x19, 0xac, 0x6c, 0x10, 0x61, 0x65, 0x5b, 0xed, 0x74, 0x3b, 0x4d, 0xa2, 0x06,
	0x51, 0x27, 0xfe, 0x0c, 0x97, 0xe3, 0x47, 0x7a, 0xf8, 0xe0, 0x72, 0xd0, 0x4b, 0xb0, 0x60, 0xee,
	0xc2, 0x8c, 0xe7, 0x0a, 0x24, 0xbb, 0xa2, 0x91, 0x01, 0xa9, 0xc1, 0xc6, 0x64, 0x44, 0x26, 0xfd,
	0xe9, 0x19, 0xf7, 0xaf, 0x1a, 0xaf, 0xcd, 0x0e, 0xfc, 0x29, 0x7f, 0x07, 0x69, 0x53, 0x78, 0x4b,
	0x5b, 0x76, 0xbc, 0x26, 0xf4, 0x78, 0xd7, 0xcf, 0x66, 0xd6, 0x19, 0x96, 0xd0, 0xc8, 0xf8, 0x2a,
	0x26, 0xa3, 0xce, 0xa4, 0x3f, 0x3d, 0xf9, 0xc3, 0x31, 0xa0, 0x69, 0x0b, 0xb2, 0x98, 0xee, 0xd7,
	0xa0, 0x8d, 0xc2, 0x65, 0xbc, 0x37, 0x22, 0x93, 0x83, 0x74, 0xd3, 0xb2, 0x01, 0xed, 0xc9, 0x12,
	0xdd, 0x6b, 0xdc, 0xf1, 0x7a, 0x68, 0xd8, 0x11, 0x8d, 0x34, 0x14, 0x0d, 0xde, 0xf5, 0x72, 0xdb,
	0x31, 0x46, 0xbb, 0x1f, 0xb8, 0x84, 0xb8, 0xe7, 0x55, 0x5f, 0xdf, 0xde, 0x7f, 0x7e, 0x77, 0xc9,
	0xfa, 0xeb, 0x9c, 0xbc, 0x5c, 0xff, 0x97, 0x50, 0x35, 0x2f, 0x76, 0x52, 0xda, 0xac, 0xba, 0x4d,
	0x2b, 0x8f, 0xfc, 0x4f, 0x5e, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x64, 0x5c, 0x08, 0x9d, 0xe9,
	0x01, 0x00, 0x00,
}

func (this *KubernetesClusterSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*KubernetesClusterSpec)
	if !ok {
		that2, ok := that.(KubernetesClusterSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Secret.Equal(that1.Secret) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *KubernetesClusterStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*KubernetesClusterStatus)
	if !ok {
		that2, ok := that.(KubernetesClusterStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Status) != len(that1.Status) {
		return false
	}
	for i := range this.Status {
		if !this.Status[i].Equal(that1.Status[i]) {
			return false
		}
	}
	if this.Version != that1.Version {
		return false
	}
	if this.Cloud != that1.Cloud {
		return false
	}
	if this.Region != that1.Region {
		return false
	}
	if this.Zone != that1.Zone {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
