// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/solo-io/skv2/api/multicluster/v1alpha1/cluster.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
	v1 "github.com/solo-io/skv2/pkg/api/core.skv2.solo.io/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//Representation of a Kubernetes cluster that has been registered.
type KubernetesClusterSpec struct {
	// name of the secret which contains the kubeconfig with information to connect to the remote cluster.
	SecretName string `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	// name local DNS suffix used by the cluster.
	// used for building FQDNs for in-cluster services
	// defaults to 'cluster.local'
	ClusterDomain string `protobuf:"bytes,2,opt,name=cluster_domain,json=clusterDomain,proto3" json:"cluster_domain,omitempty"`
	// Metadata for clusters provisioned from cloud providers.
	ProviderInfo         *KubernetesClusterSpec_ProviderInfo `protobuf:"bytes,3,opt,name=provider_info,json=providerInfo,proto3" json:"provider_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *KubernetesClusterSpec) Reset()         { *m = KubernetesClusterSpec{} }
func (m *KubernetesClusterSpec) String() string { return proto.CompactTextString(m) }
func (*KubernetesClusterSpec) ProtoMessage()    {}
func (*KubernetesClusterSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_533baf1d8d7a56a7, []int{0}
}

func (m *KubernetesClusterSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesClusterSpec.Unmarshal(m, b)
}
func (m *KubernetesClusterSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesClusterSpec.Marshal(b, m, deterministic)
}
func (m *KubernetesClusterSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesClusterSpec.Merge(m, src)
}
func (m *KubernetesClusterSpec) XXX_Size() int {
	return xxx_messageInfo_KubernetesClusterSpec.Size(m)
}
func (m *KubernetesClusterSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesClusterSpec.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesClusterSpec proto.InternalMessageInfo

func (m *KubernetesClusterSpec) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *KubernetesClusterSpec) GetClusterDomain() string {
	if m != nil {
		return m.ClusterDomain
	}
	return ""
}

func (m *KubernetesClusterSpec) GetProviderInfo() *KubernetesClusterSpec_ProviderInfo {
	if m != nil {
		return m.ProviderInfo
	}
	return nil
}

// Metadata for clusters provisioned from cloud providers.
type KubernetesClusterSpec_ProviderInfo struct {
	// Metadata specific to a cloud provider.
	//
	// Types that are valid to be assigned to ProviderInfoType:
	//	*KubernetesClusterSpec_ProviderInfo_Eks
	ProviderInfoType     isKubernetesClusterSpec_ProviderInfo_ProviderInfoType `protobuf_oneof:"provider_info_type"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *KubernetesClusterSpec_ProviderInfo) Reset()         { *m = KubernetesClusterSpec_ProviderInfo{} }
func (m *KubernetesClusterSpec_ProviderInfo) String() string { return proto.CompactTextString(m) }
func (*KubernetesClusterSpec_ProviderInfo) ProtoMessage()    {}
func (*KubernetesClusterSpec_ProviderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_533baf1d8d7a56a7, []int{0, 0}
}

func (m *KubernetesClusterSpec_ProviderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesClusterSpec_ProviderInfo.Unmarshal(m, b)
}
func (m *KubernetesClusterSpec_ProviderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesClusterSpec_ProviderInfo.Marshal(b, m, deterministic)
}
func (m *KubernetesClusterSpec_ProviderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesClusterSpec_ProviderInfo.Merge(m, src)
}
func (m *KubernetesClusterSpec_ProviderInfo) XXX_Size() int {
	return xxx_messageInfo_KubernetesClusterSpec_ProviderInfo.Size(m)
}
func (m *KubernetesClusterSpec_ProviderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesClusterSpec_ProviderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesClusterSpec_ProviderInfo proto.InternalMessageInfo

type isKubernetesClusterSpec_ProviderInfo_ProviderInfoType interface {
	isKubernetesClusterSpec_ProviderInfo_ProviderInfoType()
}

type KubernetesClusterSpec_ProviderInfo_Eks struct {
	Eks *KubernetesClusterSpec_Eks `protobuf:"bytes,1,opt,name=eks,proto3,oneof"`
}

func (*KubernetesClusterSpec_ProviderInfo_Eks) isKubernetesClusterSpec_ProviderInfo_ProviderInfoType() {
}

func (m *KubernetesClusterSpec_ProviderInfo) GetProviderInfoType() isKubernetesClusterSpec_ProviderInfo_ProviderInfoType {
	if m != nil {
		return m.ProviderInfoType
	}
	return nil
}

func (m *KubernetesClusterSpec_ProviderInfo) GetEks() *KubernetesClusterSpec_Eks {
	if x, ok := m.GetProviderInfoType().(*KubernetesClusterSpec_ProviderInfo_Eks); ok {
		return x.Eks
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*KubernetesClusterSpec_ProviderInfo) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*KubernetesClusterSpec_ProviderInfo_Eks)(nil),
	}
}

// AWS metadata associated with an EKS provisioned cluster.
type KubernetesClusterSpec_Eks struct {
	// AWS ARN.
	Arn string `protobuf:"bytes,1,opt,name=arn,proto3" json:"arn,omitempty"`
	// AWS 12 digit account ID.
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// AWS region.
	Region string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	// EKS resource name.
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubernetesClusterSpec_Eks) Reset()         { *m = KubernetesClusterSpec_Eks{} }
func (m *KubernetesClusterSpec_Eks) String() string { return proto.CompactTextString(m) }
func (*KubernetesClusterSpec_Eks) ProtoMessage()    {}
func (*KubernetesClusterSpec_Eks) Descriptor() ([]byte, []int) {
	return fileDescriptor_533baf1d8d7a56a7, []int{0, 1}
}

func (m *KubernetesClusterSpec_Eks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesClusterSpec_Eks.Unmarshal(m, b)
}
func (m *KubernetesClusterSpec_Eks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesClusterSpec_Eks.Marshal(b, m, deterministic)
}
func (m *KubernetesClusterSpec_Eks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesClusterSpec_Eks.Merge(m, src)
}
func (m *KubernetesClusterSpec_Eks) XXX_Size() int {
	return xxx_messageInfo_KubernetesClusterSpec_Eks.Size(m)
}
func (m *KubernetesClusterSpec_Eks) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesClusterSpec_Eks.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesClusterSpec_Eks proto.InternalMessageInfo

func (m *KubernetesClusterSpec_Eks) GetArn() string {
	if m != nil {
		return m.Arn
	}
	return ""
}

func (m *KubernetesClusterSpec_Eks) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *KubernetesClusterSpec_Eks) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *KubernetesClusterSpec_Eks) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type KubernetesClusterStatus struct {
	// List of statuses about the kubernetes cluster.
	// This list allows for multiple applications/pods to record their connection status.
	Status []*v1.Status `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	// The namespace in which cluster registration resources were created.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The set of PolicyRules attached to ClusterRoles when this cluster was registered.
	PolicyRules          []*PolicyRule `protobuf:"bytes,3,rep,name=policy_rules,json=policyRules,proto3" json:"policy_rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *KubernetesClusterStatus) Reset()         { *m = KubernetesClusterStatus{} }
func (m *KubernetesClusterStatus) String() string { return proto.CompactTextString(m) }
func (*KubernetesClusterStatus) ProtoMessage()    {}
func (*KubernetesClusterStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_533baf1d8d7a56a7, []int{1}
}

func (m *KubernetesClusterStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesClusterStatus.Unmarshal(m, b)
}
func (m *KubernetesClusterStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesClusterStatus.Marshal(b, m, deterministic)
}
func (m *KubernetesClusterStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesClusterStatus.Merge(m, src)
}
func (m *KubernetesClusterStatus) XXX_Size() int {
	return xxx_messageInfo_KubernetesClusterStatus.Size(m)
}
func (m *KubernetesClusterStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesClusterStatus.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesClusterStatus proto.InternalMessageInfo

func (m *KubernetesClusterStatus) GetStatus() []*v1.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *KubernetesClusterStatus) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *KubernetesClusterStatus) GetPolicyRules() []*PolicyRule {
	if m != nil {
		return m.PolicyRules
	}
	return nil
}

//
//Copy pasted from the official kubernetes definition:
//https://github.com/kubernetes/api/blob/697df40f2d58d7d48b180b83d7b9b2b5ff812923/rbac/v1alpha1/generated.proto#L98
//PolicyRule holds information that describes a policy rule, but does not contain information
//about who the rule applies to or which namespace the rule applies to.
type PolicyRule struct {
	// Verbs is a list of Verbs that apply to ALL the ResourceKinds and AttributeRestrictions contained in this rule.  VerbAll represents all kinds.
	Verbs []string `protobuf:"bytes,1,rep,name=verbs,proto3" json:"verbs,omitempty"`
	// APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
	// the enumerated resources in any API group will be allowed.
	// +optional
	ApiGroups []string `protobuf:"bytes,2,rep,name=api_groups,json=apiGroups,proto3" json:"api_groups,omitempty"`
	// Resources is a list of resources this rule applies to.  ResourceAll represents all resources.
	// +optional
	Resources []string `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	// ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.
	// +optional
	ResourceNames []string `protobuf:"bytes,4,rep,name=resource_names,json=resourceNames,proto3" json:"resource_names,omitempty"`
	// NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
	// Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
	// Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
	// +optional
	NonResourceUrls      []string `protobuf:"bytes,5,rep,name=non_resource_urls,json=nonResourceUrls,proto3" json:"non_resource_urls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyRule) Reset()         { *m = PolicyRule{} }
func (m *PolicyRule) String() string { return proto.CompactTextString(m) }
func (*PolicyRule) ProtoMessage()    {}
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_533baf1d8d7a56a7, []int{2}
}

func (m *PolicyRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyRule.Unmarshal(m, b)
}
func (m *PolicyRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyRule.Marshal(b, m, deterministic)
}
func (m *PolicyRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyRule.Merge(m, src)
}
func (m *PolicyRule) XXX_Size() int {
	return xxx_messageInfo_PolicyRule.Size(m)
}
func (m *PolicyRule) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyRule.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyRule proto.InternalMessageInfo

func (m *PolicyRule) GetVerbs() []string {
	if m != nil {
		return m.Verbs
	}
	return nil
}

func (m *PolicyRule) GetApiGroups() []string {
	if m != nil {
		return m.ApiGroups
	}
	return nil
}

func (m *PolicyRule) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *PolicyRule) GetResourceNames() []string {
	if m != nil {
		return m.ResourceNames
	}
	return nil
}

func (m *PolicyRule) GetNonResourceUrls() []string {
	if m != nil {
		return m.NonResourceUrls
	}
	return nil
}

func init() {
	proto.RegisterType((*KubernetesClusterSpec)(nil), "multicluster.solo.io.KubernetesClusterSpec")
	proto.RegisterType((*KubernetesClusterSpec_ProviderInfo)(nil), "multicluster.solo.io.KubernetesClusterSpec.ProviderInfo")
	proto.RegisterType((*KubernetesClusterSpec_Eks)(nil), "multicluster.solo.io.KubernetesClusterSpec.Eks")
	proto.RegisterType((*KubernetesClusterStatus)(nil), "multicluster.solo.io.KubernetesClusterStatus")
	proto.RegisterType((*PolicyRule)(nil), "multicluster.solo.io.PolicyRule")
}

func init() {
	proto.RegisterFile("github.com/solo-io/skv2/api/multicluster/v1alpha1/cluster.proto", fileDescriptor_533baf1d8d7a56a7)
}

var fileDescriptor_533baf1d8d7a56a7 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x5f, 0x8b, 0xd3, 0x4e,
	0x14, 0xfd, 0x65, 0xd3, 0x2d, 0xe4, 0xb6, 0xfd, 0xa9, 0x43, 0xd5, 0x58, 0x14, 0x4b, 0x41, 0x28,
	0x82, 0x09, 0xad, 0x2f, 0xbe, 0x88, 0xb0, 0x75, 0x59, 0x17, 0x41, 0x96, 0x88, 0x2f, 0x82, 0x84,
	0x69, 0x7a, 0xb7, 0x3b, 0x34, 0x9d, 0x19, 0xe6, 0x4f, 0xd9, 0xfd, 0x10, 0x7e, 0x16, 0xc1, 0x27,
	0x1f, 0xfd, 0x52, 0xfb, 0x2e, 0x99, 0x4c, 0xb3, 0x95, 0xad, 0x82, 0x4f, 0xb9, 0xf7, 0xdc, 0x93,
	0x3b, 0x67, 0xce, 0xdc, 0x0b, 0x6f, 0x96, 0xcc, 0x5c, 0xd8, 0x79, 0x52, 0x88, 0x75, 0xaa, 0x45,
	0x29, 0x5e, 0x30, 0x91, 0xea, 0xd5, 0x66, 0x9a, 0x52, 0xc9, 0xd2, 0xb5, 0x2d, 0x0d, 0x2b, 0x4a,
	0xab, 0x0d, 0xaa, 0x74, 0x33, 0xa1, 0xa5, 0xbc, 0xa0, 0x93, 0xd4, 0x03, 0x89, 0x54, 0xc2, 0x08,
	0xd2, 0xdf, 0x25, 0x25, 0x55, 0x8b, 0x84, 0x89, 0x01, 0xc1, 0x4b, 0xe3, 0xea, 0x29, 0x5e, 0x9a,
	0x9a, 0x39, 0x48, 0xfe, 0x76, 0x54, 0x21, 0x14, 0xa6, 0x9b, 0x89, 0xfb, 0xd6, 0xfc, 0xd1, 0xd7,
	0x10, 0xee, 0xbf, 0xb7, 0x73, 0x54, 0x1c, 0x0d, 0xea, 0x59, 0x7d, 0xc2, 0x47, 0x89, 0x05, 0x79,
	0x0a, 0x1d, 0x8d, 0x85, 0x42, 0x93, 0x73, 0xba, 0xc6, 0x38, 0x18, 0x06, 0xe3, 0x28, 0x83, 0x1a,
	0xfa, 0x40, 0xd7, 0x48, 0x9e, 0xc1, 0xff, 0x5e, 0x51, 0xbe, 0x10, 0x6b, 0xca, 0x78, 0x7c, 0xe0,
	0x38, 0x3d, 0x8f, 0xbe, 0x75, 0x20, 0xf9, 0x02, 0x3d, 0xa9, 0xc4, 0x86, 0x2d, 0x50, 0xe5, 0x8c,
	0x9f, 0x8b, 0x38, 0x1c, 0x06, 0xe3, 0xce, 0xf4, 0x55, 0xb2, 0xef, 0x4e, 0xc9, 0x5e, 0x2d, 0xc9,
	0x99, 0x6f, 0x70, 0xca, 0xcf, 0x45, 0xd6, 0x95, 0x3b, 0xd9, 0x80, 0x41, 0x77, 0xb7, 0x4a, 0x66,
	0x10, 0xe2, 0x4a, 0x3b, 0xb9, 0x9d, 0x69, 0xfa, 0x2f, 0x87, 0x1c, 0xaf, 0xf4, 0xbb, 0xff, 0xb2,
	0xea, 0xef, 0xa3, 0x3e, 0x90, 0xdf, 0x34, 0xe7, 0xe6, 0x4a, 0xe2, 0x60, 0x0e, 0xe1, 0xf1, 0x4a,
	0x93, 0xbb, 0x10, 0x52, 0xc5, 0xbd, 0x21, 0x55, 0x48, 0x9e, 0x00, 0xd0, 0xa2, 0x10, 0x96, 0x9b,
	0x9c, 0x2d, 0xbc, 0x0b, 0x91, 0x47, 0x4e, 0x17, 0xe4, 0x01, 0xb4, 0x15, 0x2e, 0x99, 0xe0, 0xee,
	0xea, 0x51, 0xe6, 0x33, 0x42, 0xa0, 0xe5, 0xac, 0x6d, 0x39, 0xd4, 0xc5, 0xa3, 0x6f, 0x01, 0x3c,
	0xbc, 0x2d, 0xcf, 0x50, 0x63, 0x35, 0x99, 0x40, 0x5b, 0xbb, 0x28, 0x0e, 0x86, 0xe1, 0xb8, 0x33,
	0x7d, 0x94, 0xb8, 0x87, 0xac, 0x9e, 0xb7, 0xb9, 0x5a, 0x4d, 0xcd, 0x3c, 0x91, 0x3c, 0x86, 0xa8,
	0x6a, 0xab, 0x25, 0x2d, 0x70, 0x2b, 0xac, 0x01, 0xc8, 0x0c, 0xba, 0x52, 0x94, 0xac, 0xb8, 0xca,
	0x95, 0x2d, 0x51, 0xc7, 0xa1, 0x6b, 0x3b, 0xdc, 0x6f, 0xda, 0x99, 0x63, 0x66, 0xb6, 0xc4, 0xac,
	0x23, 0x9b, 0x58, 0x8f, 0xbe, 0x07, 0x00, 0x37, 0x35, 0xd2, 0x87, 0xc3, 0x0d, 0xaa, 0x79, 0xad,
	0x31, 0xca, 0xea, 0xc4, 0x39, 0x24, 0x59, 0xbe, 0x54, 0xc2, 0x4a, 0x1d, 0x1f, 0xb8, 0x52, 0x44,
	0x25, 0x3b, 0x71, 0x40, 0x25, 0x53, 0xa1, 0x16, 0x56, 0x15, 0x5e, 0x45, 0x94, 0xdd, 0x00, 0xd5,
	0xa0, 0x6d, 0x13, 0x37, 0x8b, 0x3a, 0x6e, 0x39, 0x4a, 0x6f, 0x8b, 0x56, 0xe3, 0xa8, 0xc9, 0x73,
	0xb8, 0xc7, 0x05, 0xcf, 0x1b, 0xaa, 0x55, 0xa5, 0x8e, 0x0f, 0x1d, 0xf3, 0x0e, 0x17, 0x3c, 0xf3,
	0xf8, 0x27, 0x55, 0xea, 0xa3, 0x93, 0x1f, 0xd7, 0xad, 0xe0, 0xe7, 0x75, 0x2b, 0xf8, 0xfc, 0xfa,
	0x4f, 0x0b, 0x23, 0x57, 0xcb, 0x5b, 0xfb, 0xb9, 0x35, 0xa3, 0xd9, 0xd3, 0x79, 0xdb, 0xad, 0xd1,
	0xcb, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x59, 0x3f, 0x10, 0xce, 0xe3, 0x03, 0x00, 0x00,
}
