// Code generated by skv2. DO NOT EDIT.

// Definitions for the Kubernetes types
package v1beta1

import (
    . "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
)

// CustomResourceDefinitionSlice represents a slice of *CustomResourceDefinition
type CustomResourceDefinitionSlice []*CustomResourceDefinition
