// Code generated by skv2. DO NOT EDIT.

// Definitions for the Kubernetes types
package v1

import (
	. "k8s.io/api/core/v1"
)

// SecretSlice represents a slice of *Secret
type SecretSlice []*Secret

// ServiceAccountSlice represents a slice of *ServiceAccount
type ServiceAccountSlice []*ServiceAccount

// NamespaceSlice represents a slice of *Namespace
type NamespaceSlice []*Namespace
